---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chef
  require_chef_omnibus: 12.7.2
  data_bags_path: test/fixtures/data_bags
  environments_path: test/fixtures/environments
  encrypted_data_bag_secret_key_path: test/fixtures/data_bags/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64

suites:
  - name: default
    run_list:
      recipe[opsline-users::default]
    attributes:
      opsline-users:
        users_databag_name: users
        groups_databag_name: groups
  - name: environments
    run_list:
      recipe[opsline-users::default]
    attributes:
      opsline-users:
        users_databag_name: environments
        groups_databag_name: groups
    provisioner:
      client_rb:
        environment: production

